# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Portfolio
email: orlando.vivanco@Gearboxsoftware.com
description: > # this means to ignore newlines until "baseurl:"
  Orlando Aguilar Vivanco Portfolio. Graphics and game programmer.
baseurl: /
github_username:  OrlandoAguilar
BASE_PATH: _post
# Build settings
markdown: orlandoaguilar
include: ["./Portfolio/interactive/*"]
